language: ruby
cache:
  - bundler
env:
  global:
    - RAILS_ENV=development
matrix:
  include:
    - rvm: 2.1
      env: RAILS_VERSION="~> 4.2.7"
    - rvm: 2.2
      env: RAILS_VERSION="~> 4.2.7"
    - rvm: 2.2
      env: RAILS_VERSION="~> 5.0.0"
    - rvm: 2.3.3
      env: RAILS_VERSION="~> 4.2.7"
    - rvm: 2.3.3
      env: RAILS_VERSION="~> 5.0.0"
    - rvm: 2.4.0
      env: RAILS_VERSION="~> 5.0.0"
before_install: gem install bundler -v "~> 1.17" --no-document
